### ISSUE TITLE
Sony Xperia XZ2 crash on launch [BUG_CRASH]

### ISSUE THREAD

**Issue by mondstern** [tty7-tyrone/LongShootAlpha#2]
my phone: sony xperia xz2, android 9.0, model H8266
i want install the app: 
allow to take pictures and videos? allow. this works out.
allow access to photos, media and files on your device? allow. this works out
allow to retrieve the device status? allow. and then the app just quits.
During the query I see slightly transparent but the app in the background.
but then just close the app

**Comment by CKH4** [comment]
I can't reproduce this. Does your device have camera2? You can check with an [app](https://play.google.com/store/search?q=camera2%20probe&c=apps).

**Comment by gargamelak47** [comment]
Same problem on Note 4 with Lineage 15.1

12-31 23:10:40.778 E/AndroidRuntime(24463): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.tyroneil.longshootalpha/com.tyroneil.longshootalpha.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference

12-31 23:15:30.786 E/AndroidRuntime(25493): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tyroneil.longshootalpha/com.tyroneil.longshootalpha.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference

**Comment by CKH4** [comment]
You need a specific api called camera2 to be enabled on your device. Only your device manufacturer can enable it.

@gargamelak47 is it the Galaxy Note 4 or the Redmi Note 4? I know that this will not work on the Galaxy Note 4, however it may or may not work on a Redmi Note 4

**Comment by Tyrone-Liu** [comment]
> Same problem on Note 4 with Lineage 15.1
> 
> 12-31 23:10:40.778 E/AndroidRuntime(24463): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.tyroneil.longshootalpha/com.tyroneil.longshootalpha.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
> 
> 12-31 23:15:30.786 E/AndroidRuntime(25493): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tyroneil.longshootalpha/com.tyroneil.longshootalpha.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference

@gargamelak47 Does the stack trace lead to any specific lines?

**Comment by Tyrone-Liu** [comment]
@mondstern Something must gone wrong, that is somehow expected...  I need more information to help you, like stack trace or something.

I will make some updates to the `README.md` file or create an issue template to describe how to provide useful information.

**Comment by Tyrone-Liu** [comment]
**Guys, I'm new to Android and I do not have many different devices to properly test compatibility.**

**Comment by Tyrone-Liu** [comment]
@CKH4 This APP works on some of your devices?

**Comment by CKH4** [comment]
Yeah, I have an Axon 7 on lineageos 15.1 which has level 3 camera2 support. I had to manually create `DCIM/LongShoot`. That's the only bug I've had when running

**Comment by CKH4** [comment]
[ ] On OnePlus 6 (enchilada), when the image format is RAW_SENSOR, the preview viewfinder will get anomalously brighter, but the captured image still have normal brightness.

Possibly this, however I'm not sure.

[ ] When the image format is RAW_SENSOR, the 'captureSize' acquired from 'cameraCharacteristics' will be slightly bigger than then actual result.

I don't think I've seen this, however I think this may have something to do with EIS. I've experienced something like this in the past where images are lower than the maximum resolution of the camera sensor.

**Comment by Tyrone-Liu** [comment]
For the first one, if you have other camera app that can manually set exposure time, ISO and aperture (if available), set the same thing, then compare (maybe in multitask view).  It is brighter on OP6, but not on Nexus 6P, and **it's not like over exposed**, it feels not natural.  (and a bit plane?)

For the second one, smaller than sensor resolution is actually normal, there is `SENSOR_INFO_ACTIVE_ARRAY_SIZE` to cut off, and different output size for different format.  On the terrible OnePlus 6, it has a 16MP sensor, only have 12MP maximum output with JPEG.  
The bug I'm referring to is that the size of result image is not even in the output sizes list from `SCALER_STREAM_CONFIGURATION_MAP`, a few pixel been cut at the edge.

**Comment by Tyrone-Liu** [comment]
> Same problem on Note 4 with Lineage 15.1
> 
> 12-31 23:10:40.778 E/AndroidRuntime(24463): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.tyroneil.longshootalpha/com.tyroneil.longshootalpha.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
> 
> 12-31 23:15:30.786 E/AndroidRuntime(25493): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tyroneil.longshootalpha/com.tyroneil.longshootalpha.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference

@gargamelak47 It seems like this happened when dealing with the permission request.

**There is nothing related to `float` in that part of code, unless** on your device java somehow choose `arrayIndexOf(float[] array, float value)` over `static int arrayIndexOf(String[] array, String value)` when I explicitly pass `String[]` and `String` to it, which makes no sense.

Please try to grant permissions in system `app info` interface (not in run time permission request), then launch the app, see if it crashes.

**Comment by mondstern** [comment]
there is news: so when I have the app installed, only queries such as approval on memory and on media access.
if I agree with the permissions, the app exits (that's what I first wrote).
But if I do not agree with all the permissions, no error comes: the app starts See link :.
https://abload.de/img/longshotxrcqu.jpg
positive: it goes schonmal further than last time.
negative: picture does not work.

I will contact you again if I have news on my part.

**Comment by Tyrone-Liu** [comment]
> there is news: so when I have the app installed, only queries such as approval on memory and on media access.
> if I agree with the permissions, the app exits (that's what I first wrote).
> But if I do not agree with all the permissions, no error comes: the app starts See link :.
> https://abload.de/img/longshotxrcqu.jpg
> positive: it goes schonmal further than last time.
> negative: picture does not work.
> 
> I will contact you again if I have news on my part.

**Of course the picture will not work without camera access.**  I explicitly programmed that to prevent crash when user refuse to grant camera access.

@mondstern I need you to **let it crash**, and [collect the logcat produced by the crash](https://github.com/Tyrone-Liu/LongShootAlpha/blob/master/README.md#how-to-get-the-logcat), that can really help me find out the cause.

**Comment by mondstern** [comment]
but if i give camera access then crash the app. So I'll keep trying.

**Comment by Tyrone-Liu** [comment]
> but if i give camera access then crash the app. So I'll keep trying.

No, it crash because there is some bug I can not produce on my own device.  So, **I need your help to find out what makes it crash.**  To do that, you need to **let it crash**, collect the log then send the log to me.

**Comment by mondstern** [comment]
and how can i collect the log ?

**Comment by Tyrone-Liu** [comment]
> and how can i collect the log ?

It is described [here](https://github.com/Tyrone-Liu/LongShootAlpha/blob/master/README.md#how-to-get-the-logcat) (<-- that is clickable).

But if you have never heard of `adb`, I think collecting log may be too much to do.  So you can wait for me to refine the compatibility checking app, then check if it is a compatibility issue.

**Comment by mondstern** [comment]
yes i have never heard of adb ;-( 
so i must wait to an update or another notes

**Comment by Tyrone-Liu** [comment]
There is a high possibility the crash is a compatibility issue.  If that's true, I'm sorry updates can't fix it.  Just wait for me to refine the checker.

**Comment by Tyrone-Liu** [comment]
@mondstern Try this APK [googlesamples_android-Camera2Basic.zip](https://github.com/Tyrone-Liu/LongShootAlpha/files/2725661/googlesamples_android-Camera2Basic.zip).  If it at lest lets you see the camera preview, it should means your device support camera2 API.

However, if it doesn't work, I still needs to write my own checker.
